# Generated by Django 5.2.4 on 2025-10-13 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_variation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variation',
            old_name='varitation_value',
            new_name='variation_value',
        ),
    ]
